### ISSUE TITLE
Verzija Codeigniter-a

### ISSUE THREAD

**Issue by MilosZivkovic** [ictcollege/ictcloud#1]
Profesor je rekao da stavimo najnoviju verziju Codeigniter-a a ne 2.2.0

**Comment by vhristodulo** [comment]
ok, ali dosta ima izmena u odnosu na 2.x verziju, cak i neke bagove... http://www.codeigniter.com/user_guide/changelog.html (verzija 3 se reklamira kao active development verzija)
mislim da je bolje da radimo na verziji na kojoj smo vec radili u skoli da ne bi gubili vreme, a sutra mozemo da pricamo sa profesorom o tome, pa cemo lako da promenimo verziju ako je potrebno.
pozdrav
